language: node_js
node_js:
  - "v5.7.1"

services:
  - mongodb

before_script:
  - "npm install -g webpack eslint karma"
  - "npm install"

script:
  - sleep 5
  - "make test FILE=./src/api/**/__tests__/*-test.js"
  - "npm run test"
  - "npm run lint"